apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  labels:
    app: odoo
data:
  odoo.conf: |
    [options]
    admin_passwd = {{ .Values.odoo.adminPassword }}
    db_host = {{ .Values.postgresql.service.name }}
    db_port = 5432
    db_user = {{ .Values.postgresql.auth.username }}
    db_password = {{ .Values.postgresql.auth.password }}
    addons_path = /usr/lib/python3/dist-packages/odoo/addons
    logfile = /var/log/odoo/odoo-server.log
    log_level = {{ .Values.odoo.logLevel }}
    data_dir = /var/lib/odoo
    http_port = 8069
    http_interface = 0.0.0.0
    list_db = False
    proxy_mode = True
    workers = {{ .Values.odoo.workers }}
    max_cron_threads = 1
    limit_memory_hard = 2684354560
    limit_memory_soft = 2147483648
    limit_request = 8192
    limit_time_cpu = 600
    limit_time_real = 1200 