# Postfix
version: '3'

services:
  # Postgres
  # Use postgres/example user/password credentials
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # Redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  # Pretix
  pretix:
    image: pretix/standalone:stable
    volumes:
      - ./pretix-data:/data
      - ./etc:/etc/pretix
    ports:
    - 8081:80
    environment:
      PRETIX_HOSTNAME: ${PRETIX_HOSTNAME}
    labels:
      traefik.enable: "true"
      traefik.http.routers.pretix.rule: "Host(`hu.technotuev.de`)"
      traefik.http.routers.pretix.entrypoints: "websecure"
      traefik.http.routers.pretix.tls: "true"
      traefik.http.routers.pretix.tls.certresolver: "letsencrypt"
      traefik.http.routers.pretix.service: "pretix"
      traefik.http.services.pretix.loadbalancer.server.port: 8081
    networks:
      - proxy

volumes:
  db-data:
  redis-data:

networks:
    pretix:
      driver: bridge
    proxy:
      external: true