# Postfix
version: '3'

services:
  # Postgres
  # Use postgres/example user/password credentials
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    labels:
      traefik.enable: "false"
    networks:
      - pretix
  postgres-backup:
    volumes:
      - /var/backup:/var/backup
      - ./backup_script.sh:/backup_script.sh
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${PRETIX_POSTGRES_DB}
    command: >
      bash -c "chmod +x /backup_script.sh && /backup_script.sh"
    networks:
      - pretix
  # Redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - pretix
    labels:
      traefik.enable: "false"

  # Pretix
  pretix:
    image: pretix/standalone:stable
    volumes:
      - pretix-data:/data
      - ./etc:/etc/pretix
    ports:
    - "8081:80"
    environment:
      PRETIX_HOSTNAME: ${PRETIX_HOSTNAME}
    networks:
      - proxy
      - pretix
    labels:
      traefik.enable: "true"
      # TLS Router and configuration
      traefik.http.routers.pretix-https.rule: "Host(`hu.technotuev.de`)"
      traefik.http.routers.pretix-https.tls: "true"
      traefik.http.routers.pretix-https.tls.certresolver: "letsencrypt"

      # HTTP Router configuration
      treafik.http.routers.pretix-http.rule: "Host(`hu.technotuev.de`)"
      treafik.http.routers.pretix-http.entrypoints: "web"
      # Create a middleware named `redirect-to-https` middleware to redirect from http to https
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"
      # Apply the middleware named `redirect-to-https` to the router named `pretix`
      traefik.http.routers.pretix-http.middlewares: "redirect-to-https"

volumes:
  db-data:
  redis-data:
  pretix-data:

networks:
    pretix:
    proxy:
      external: true