CREATE USER POSTGRES_USER WITH PASSWORD 'POSTGRES_PASSWORD';
CREATE DATABASE POSTGRES_DB ENCODING UTF8;
GRANT ALL PRIVILEGES ON DATABASE POSTGRES_DB TO POSTGRES_USER;
ALTER DATABASE POSTGRES_DB OWNER TO POSTGRES_USER;