-- Create Pretix user
CREATE USER ${PRETIX_POSTGRES_USER} WITH PASSWORD '${PRETIX_POSTGRES_PASSWORD}';
CREATE DATABASE ${PRETIX_PRETIX_POSTGRES_DB} ENCODING UTF8;
GRANT ALL PRIVILEGES ON DATABASE ${PRETIX_POSTGRES_DB} TO ${PRETIX_POSTGRES_USER};
ALTER DATABASE ${PRETIX_POSTGRES_DB} OWNER TO ${PRETIX_POSTGRES_USER};