apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: admin-password
        - name: PRETIX_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: pretix-user
        - name: PRETIX_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: pretix-password
        - name: PRETIX_POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: pretix-db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        {{- if .Values.postgres.initScript.enabled }}
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        {{- end }}
      volumes:
      - name: postgres-data
        {{- if .Values.postgres.persistence.enabled }}
        persistentVolumeClaim:
          claimName: postgres-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.postgres.initScript.enabled }}
      - name: init-script
        configMap:
          name: postgres-init-script
      {{- end }} 