apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.postgres.adminPassword }}
  pretix-user: {{ .Values.secrets.postgres.pretixUser }}
  pretix-password: {{ .Values.secrets.postgres.pretixPassword }}
  pretix-db: {{ .Values.secrets.postgres.pretixDb }} 