global:
  ingress:
    className: &className public

dns:
  client: &client doppelschicht.der-ttn.de
  api: &api doppelschicht-api.der-ttn.de
  keycloak: &keycloak connect.der-ttn.de

  
api:
  image:
    tag: "v1.2.10"
  baseURL: *api
  authority: *keycloak
  corsOrigins0: localhost,https://*keycloak,https://*client
  ingress:
    enabled: true
    className: *className
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.der-ttn.de"
      nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, OPTIONS, DELETE"
      nginx.ingress.kubernetes.io/cors-allow-headers: "Accept,Authorization,Content-Type,Locatee-Smart-Signage-Token"
      nginx.ingress.kubernetes.io/cors-max-age: "100"
    hosts:
      - host: *api
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - *api
      - *client
      secretName: tls-secret


client:
  keycloakOverrideBaseUrl: *keycloak
  image:
    tag: "v1.2.9"
  api:
    baseURL: *api
    corsOrigins0: 
      - localhost
      - *keycloak
      - *client
  manifest:
    name: Techno TÜV Nord Schichtplanner
    shortName: TTN-shifts
  customization:
    app:
      title: Techno TÜV Nord - Schichtplanner
      subtitle: Bass. Liebe. Doppelschicht.
      startTime: 10:00:00
      endTime: 28:00:00
      contact: arne@technotuev.de
  favicon:
    binaryData:
      ico: iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAzVJREFUaEPtmLsvc2Ecx791jxYRIqk0/RsMJawWJB0sErelNI2IgS4MSMREYjJU0nSRDsLonphIdKvB5pqGIBEJoWhd+uZ7kvPEeRXv22foOXJ+i3jOc/v8vs/vggVACgY2iwmQZfVMBbIsAEwFTAUkPWA+IUkHSi83FZB2oeQGv0sBi8UCq9WK3NxcSb98v/zp6QnJZPLHM0pLS8E7qfb+/o54PA7+VE2jABcEAgHU1NT8uHmmE1KpFKLRKPr7+/Hw8PDlNsXFxdjY2EBFRYWYE4vF4PP5cH5+nh6gvLwcq6uraGhoyPR+/7SOEMvLy/B6vbi+vk67xmaz4fj4GFVVVeL70dERmpqacHJykl0Anv7y8oLFxUWMjIxoPKreTPcAVIFxsLW1BY/H80mJjADKysoQCoU0McCxyspKIRkPvr+/x83NjQgmBlp1dTWKiorEvLe3N1xeXiKRSIixwsJCZV5OTo7m2Wxvb6O7uxtnZ2diPCMAXqSkpAT5+flio97eXkxNTWkA5ufnMTo6CmYTGtetra2htrZWzLu7u0Nrayv29/fFGJPDysqKBpQfCbu+vg6/34/Dw0NlfkYA6aJpYGAAs7OzGoBgMIihoSE8Pj4KgN3dXdTX14t5t7e3aGxsxN7enhhzuVzY2dn5BMAJr6+viEQi6OzsVGLCcAAqJVMsIS4uLsCs819ZKJsKqGezSFGl8fFxLC0t6R+AF2YMfay4jAnGgtPpBAuaaj/WgWwowAzEeGlpaUFeXp4G5O/76BKAlZ91YGZmBm1tbWkDXNcKEMDtdsNutysQ7e3tX6qgWwUIQGOhm5ubQ0dHBwoKCj6B6B6AEOyIJycnlUbvYwDzmyEAeFG20BMTE0rL/TE7GQaAEMxI09PT6OvrUwKbIIYCIASf0PDwMAYHB5WnZTgAQrC5ZJM3NjaG09PT7/+gSVfI6urq0NzcrGnm2K9sbm4qDZhqPT09cDgc4vfn52ewa726uhJjTJXM+Xweqh0cHGBhYSHd0WKM7XdXVxfY2ofDYaXwqfa7/ivxrRt0+tFUINvCmAqYCkh6wHxCkg6UXm4qIO1CyQ1MBSQdKL3c8Ar8AXw36x/XsOmjAAAAAElFTkSuQmCC
      png: iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAAAXNSR0IArs4c6QAACJtJREFUeF7tnf8xNVkQhkcGMkAGMkAIIkAEiAARIAJEgAgIQQaEIANf9d1Vu7Xrx3t7zkz3uf1M1Vf7z+3TfZ73PHWXe2esDcPwMXBBAAJfElhDEE4GBL4ngCCcDgj8QABBOB4QQBDOAAR8BHgH8XGjqggBBCkSNNv0EUAQHzeqihBAkCJBs00fAQTxcaOqCAEEKRI02/QRQBAfN6qKEECQIkGzTR8BBPFxo6oIAQQpEjTb9BFAEB83qooQQJAiQbNNHwEE8XGjqggBBCkSNNv0EUAQHzeqihBAkCJBs00fAQTxcaOqCAEEKRI02/QRQBAfN6qKEECQIkGzTR8BBPFxo6oIAQQpEjTb9BFAEB83qooQQJAiQbNNHwEE8XGjqggBBCkSNNv0EUAQHzeqihBAkCJBs00fAQTxcaOqCAEEKRI02/QRQBAfN6qKEECQIkGzTR8BBPFxo6oIAQQpEjTb9BFAEB83qooQQJAiQbNNHwEE8XGjqggBBCkSNNv0EUAQHzeqihBAkCJBs00fAQTxcaOqCAEEKRI02/QRQBAfN6qKEECQIkGzTR8BBPFxo6oIAQQpEjTb9BFAEB83qooQQJAiQbNNHwEE8XGjqggBBCkSNNv0EUAQHzeqihBAkCJBs00fAQTxcaOqCAEEKRI02/QRaCLIx8eHrztVsxF4eXkZ9vb2hvf399l6LtPo8PBwuLm5Wabk19deXFwM5+fnv77upxcgyCh8fRVnlgRB+jpLKzttVkkQZGWPXH8be3t7W/zvlv03y4UgWZJgjgWBbJIgCAczHYFMkiBIuuPBQJneSRCE85iWQIZ3EgRJezwYLMM7CYJwDtMTiHwnQZD0x4MBI99JEITz1w0B+zqKfU5iHyrOdSHIXKTp04TA3JIgSJPYWGROAnNKgiBzJkuvZgRMkqOjo+Hh4aHZml8thCCT4mXxqQnYAb67u5usDYJMhpaF5yIwpSQIMleK9JmUwFSSIMiksbH4nAROT0+Hq6urpi1XWpCxtzV+kl5fXx+Oj4+bgrcfMq+vr5usubGxMViQLS/7rOHx8bHJkjs7O8Pu7m6TtX5bxDK3W1pbXSstSCtIm5ubw+vra6vlFuvY1ye2traarGmH7+npqclan4vc3t4ufkvU4rJDe3Z21mIpaY2WkiCIgBxBBEg/vGRuQWyUVpIgiJA9ggiQkgnSShIEEbJHEAFSQkFaSIIgQvYIIkBKKshYSRBEyB5BBEiJBRkjCYII2SOIACm5IDaefUZin5UscyGIQAtBBEgdCGIjLvvrawQRskcQAVIngiwrCYII2SOIAKkjQZaRBEGE7BFEgNSZIDau8jxgBBGyRxABUoeCKJIgiJA9ggiQOhXkN0kQRMgeQQRIHQvyKcn+/v7/niyPIEL2CCJA6lwQG/+rB9QhiJA9ggiQVkCQryRBECF7BBEgrYgg/5UEQYTsEUSAtEKC/FsSuxltZf+I57hY/6lGkHEkI26YGjfxX9X2M4l9NaXVrdufM6X5K7ctINkaCDKOZK+CjNv199UIIpDlnnQB0oq+BEGEYBFEgPTDS+yQHRwcLN7de7sQREgMQQRIP7zEnrjy/Py8eJpLb5IgiJA9ggiQfhHEfoA2OXqTBEGE7BFEgCQI8vlLlJ4kQRAhewQRIImC9CYJggjZI4gAaQlBepIEQYTsEUSAtKQgvUiCIEL2CCJAcgjSgyQIImSPIAIkpyBWZk/ktx/ct7e3xzWaoBpBBKgIIkAaIUhmSRBEyB5BBEgjBckqCYII2SOIAKmBIBklQRAhewQRIDUS5HMZ++Tdvr8VfSGIkACCCJAaC2LLZZAEQYTsEUSANIEgGSRBECF7BBEgTSSILWtPem/9h1nVHSGIQApBBEgTCmJLR93piCBC9ggiQJpYkChJEETIHkEESDMIEiEJggjZI4gAaSZB5pYEQYTsEUSANKMgc0qCIEL2CCJAmlmQuSRBECF7BBEgBQgyhyQIImSPIAKkIEGs7cnJyXB5eTluyG+qEUTAiiACpEBBrPUUD662dRFEyB5BBEjBgkwlCYII2SOIACmBIFNIgiBC9ggiQEoiiI1hfwbh/v5+cSvv2AtBBIIIIkBKJIiNYve3233uYyVBECF7BBEgJROklSQIImSPIAKkhIK0kARBhOwRRICUVBAba8xDsxFEyB5BBEiJBRkjCYII2SOIACm5IF5JEETIHkEESB0I4pEEQYTsEUSA1Ikgy0qCIEL2CCJA6kiQZSRBECF7BBEgdSaIKgmCCNkjiACpQ0EUSVZOEPtqQevH6L+/vw8vLy/jTsnf1VPMZwLbvxaXfWbQ+i/RGjtjmPX6KZMWbNeGYfjIunnmgkA0AQSJToD+qQkgSOp4GC6aAIJEJ0D/1AQQJHU8DBdNAEGiE6B/agIIkjoehosmgCDRCdA/NQEESR0Pw0UTQJDoBOifmgCCpI6H4aIJIEh0AvRPTQBBUsfDcNEEECQ6AfqnJoAgqeNhuGgCCBKdAP1TE0CQ1PEwXDQBBIlOgP6pCSBI6ngYLpoAgkQnQP/UBBAkdTwMF00AQaIToH9qAgiSOh6GiyaAINEJ0D81AQRJHQ/DRRNAkOgE6J+aAIKkjofhogkgSHQC9E9NAEFSx8Nw0QQQJDoB+qcmgCCp42G4aAIIEp0A/VMTQJDU8TBcNAEEiU6A/qkJIEjqeBgumgCCRCdA/9QEECR1PAwXTQBBohOgf2oCCJI6HoaLJoAg0QnQPzUBBEkdD8NFE0CQ6ATon5oAgqSOh+GiCSBIdAL0T00AQVLHw3DRBBAkOgH6pyaAIKnjYbhoAggSnQD9UxNAkNTxMFw0AQSJToD+qQkgSOp4GC6aAIJEJ0D/1AQQJHU8DBdNAEGiE6B/agIIkjoehosmgCDRCdA/NQEESR0Pw0UTQJDoBOifmgCCpI6H4aIJIEh0AvRPTeAPKKivan6BlkAAAAAASUVORK5CYII=
  ingress:
    enabled: true
    className: *className
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: *client
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - *api
      - *client
      secretName: tls-secret


keycloak:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    ingressClassName: *className
    hostname: *keycloak
    tls: true
