global:
  ingress:
    className: &className public

dns:
  client: &client doppelschicht.der-ttn.de
  api: &api doppelschicht-api.der-ttn.de
  keycloak: &keycloak connect.der-ttn.de

  
api:
  baseURL: *api
  corsOrigins0:
    - localhost
    - *keycloak
    - *client
  ingress:
    enabled: true
    className: *className
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: *api
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - *api
      - *client
      secretName: tls-secret


client:
  keycloakOverrideBaseUrl: *keycloak
  api:
    baseURL: *api
    corsOrigins0: 
      - localhost
      - *keycloak
      - *client
  manifest:
    name: Techno TÜV Nord Schichtplanner
    shortName: TTN-shifts
  ingress:
    enabled: true
    className: *className
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: *client
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - *api
      - *client
      secretName: tls-secret


keycloak:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    ingressClassName: *className
    hostname: *keycloak
    tls: true
