global:
  ingress:
    className: &className public

dns:
  client: &client doppelschicht.der-ttn.de
  api: &api doppelschicht-api.der-ttn.de
  keycloak: &keycloak connect.der-ttn.de

  
api:
  image:
    tag: "v1.2.10"
  baseURL: *api
  corsOrigins0: localhost,https://*keycloak,https://*client
  ingress:
    enabled: true
    className: *className
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.der-ttn.de"
      nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, OPTIONS, DELETE"
      nginx.ingress.kubernetes.io/cors-allow-headers: "Accept,Authorization,Content-Type,Locatee-Smart-Signage-Token"
      nginx.ingress.kubernetes.io/cors-max-age: "100"
    hosts:
      - host: *api
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - *api
      - *client
      secretName: tls-secret


client:
  keycloakOverrideBaseUrl: *keycloak
  image:
    tag: "v1.2.9"
  api:
    baseURL: *api
    corsOrigins0: 
      - localhost
      - *keycloak
      - *client
  manifest:
    name: Techno TÜV Nord Schichtplanner
    shortName: TTN-shifts
  ingress:
    enabled: true
    className: *className
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: *client
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - *api
      - *client
      secretName: tls-secret


keycloak:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    ingressClassName: *className
    hostname: *keycloak
    tls: true
