secrets:
  keycloak:
    auth:
      enabled: true
      name: keycloak-auth-credentials
  postgresql:
    enabled: true
    name: &postgresql-secret "postgresql-secret"
  muddi-admin:
    name: muddi-admin-pw


api:
  enabled: true
  database:
    existingPasswordSecret: *postgresql-secret
    existingPasswordSecretKey: "shiftplanner-password"
  keycloakOverrideBaseUrl: ""
  corsOrigins0: 
    - localhost


client:
  enabled: true
  admin:
    existingSecret: muddi-admin-pw
    existingSecretKey: MuddiConnect__AdminPassword
  manifest:
    name:
    shortName:


postgresql:
  enabled: true
  nameOverride: shiftplanner-postgresql
  fullnameOverride: shiftplanner-postgresql
  auth:
    existingSecret: postgresql-secret
  primary:
    initdb:
      scriptsSecret: pg-init
    resources:
      limits:
        cpu: "300m"
        memory: "512Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
  serviceAccount:
    create: true


keycloak:
  enabled: true
  externalDatabase:
    existingSecret: postgresql-secret
    existingSecretPasswordKey: keycloak-password
    host: shiftplanner-postgresql
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  ingress:
      servicePort: 80
  auth:
    existingSecret: keycloak-auth-credentials
  startupProbe:
    enabled: true
  postgresql:
    enabled: false
  keycloakConfigCli:
    enabled: false
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    existingConfigmap: keycloak-realm-configmap

