apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  labels:
    app: odoo
data:
  odoo.conf: |
    [options]
    addons_path = {{ .Values.odoo.config.addons_path }}
    admin_passwd = {{ .Values.odoo.config.admin_passwd }}
    db_host = postgresql-ha-postgresql
    db_port = 5432
    db_user = {{ .Values.postgresql-ha.auth.username }}
    db_password = ${ODOO_POSTGRES_PASSWORD}
    db_name = postgres 