apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  type: ClusterIP
  ports:
  - port: 8069
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: odoo 