apiVersion: batch/v1
kind: Job
metadata:
  name: shiftplanner-db-init
  labels:
    app: shiftplanner
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:15
        command: ["/bin/sh", "-c"]
        args:
        - |
          #!/bin/sh
          set -e
          
          # Wait for PostgreSQL to be ready
          until pg_isready -h shiftplanner-postgresql -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          
          # Initialize database
          psql -h shiftplanner-postgresql -U postgres -f /scripts/init-shiftplanner.sql
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: shiftplanner-postgresql
              key: postgres-password
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
      volumes:
      - name: init-scripts
        configMap:
          name: shiftplanner-db-init
      restartPolicy: OnFailure 