{{- $adminPw := (randAlpha 16) | b64enc | quote }}
{{- $managementPw := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.keycloak.auth.existingSecret) }}
{{- if $secret }}
{{- $adminPw = index $secret.data "admin-password" }}
{{- $managementPw = index $secret.data "management-password" }}
{{- end -}}

{{- if or $secret (and .Values.keycloak.enabled .Values.secrets.keycloak.auth.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.keycloak.auth.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  admin-password: {{ $adminPw }}
  management-password: {{ $managementPw }}
{{- end -}}
