apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.keycloak.adminPassword }}
  postgres-password: {{ .Values.secrets.keycloak.postgresPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  password: {{ .Values.secrets.postgres.password }}
  muddi-user: {{ .Values.secrets.postgres.muddiUser }}
  muddi-password: {{ .Values.secrets.postgres.muddiPassword }}
  muddi-db: {{ .Values.secrets.postgres.muddiDb }} 