apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiftplanner-client
  labels:
    app: shiftplanner-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiftplanner-client
  template:
    metadata:
      labels:
        app: shiftplanner-client
    spec:
      containers:
      - name: shiftplanner-client
        image: {{ .Values.shiftPlannerClient.image.repository }}:{{ .Values.shiftPlannerClient.image.tag }}
        volumeMounts:
        {{- range .Values.shiftPlannerClient.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      {{- range .Values.shiftPlannerClient.volumes }}
      - name: {{ .name }}
        {{- if .configMap }}
        configMap:
          name: {{ .configMap.name }}
        {{- end }}
      {{- end }} 