apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pretix-backup-pvc
  labels:
    app: pretix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storage | default "10Gi" }} 