name: "Pretix deploy"

on:
  push:
    branches:
      - main
jobs:
  scp-files:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: replace
        # create a job step replace env variables in init.sql and pretix.cfg
        # TODO: Mailconfig
        run: |
          sed -i "s/PRETIX_POSTGRES_USER/${{ secrets.PRETIX_POSTGRES_USER }}/g" pretix/init.sql
          sed -i "s/PRETIX_POSTGRES_DB/${{ secrets.PRETIX_POSTGRES_DB }}/g" pretix/init.sql
          sed -i "s/PRETIX_POSTGRES_PASSWORD/${{ secrets.PRETIX_POSTGRES_PASSWORD }}/g" pretix/init.sql
         
          sed -i "s/PRETIX_POSTGRES_USER/${{ secrets.PRETIX_POSTGRES_USER }}/g" pretix/pretix.cfg
          sed -i "s/PRETIX_POSTGRES_DB/${{ secrets.PRETIX_POSTGRES_DB }}/g" pretix/pretix.cfg
          sed -i "s/PRETIX_POSTGRES_PASSWORD/${{ secrets.PRETIX_POSTGRES_PASSWORD }}/g" pretix/pretix.cfg
          
          sed -i "s/PRETIX_HOSTNAME/${{ env.PRETIX_HOSTNAME }}/g" pretix/pretix.cfg
          sed -i "s/PRETIX_INSTANCE_NAME/${{ env.PRETIX_INSTANCE_NAME }}/g" pretix/pretix.cfg

          sed -i "s/POSTGRES_ADMIN_PASSWORD/${{ env.POSTGRES_ADMIN_PASSWORD }}/g" pretix/docker-compose.yml

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "install.sh, pretix/, traefik/, backups/"
          target: opt/
  provision:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    needs:
      - scp-files
    steps:
      - name: Spin up traefik and pretix
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            # Create volumes for docker
            chown -R 15371:15371 /opt/pretix/pretix-data/
            chown -R 15371:15371 /opt/pretix/etc/
            # etc folder and config file
            chmod 0700 /opt/pretix/etc/pretix.cfg
            # Docker stack deploys
            docker stack deploy -c traefik/docker-compose.yml traefik
            docker stack deploy -c pretix/docker-compose.yml pretix