name: "Pretix deploy"

on:
  push:
    branches:
      - main
jobs:
  scp-files:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Replace env variables in init.sql for pretix postgres database
        run: |
          sed -i '' "s/\${PRETIX_POSTGRES_USER}/test123/g" pretix/init.sql
          sed -i '' "s/\${PRETIX_POSTGRES_USER}/${{ secrets.PRETIX_POSTGRES_USER }}/g"  pretix/init.sql
          sed -i '' "s/\${PRETIX_POSTGRES_USER}/${{ secrets.PRETIX_POSTGRES_USER }}/g" pretix/init.sql
          sed -i '' "s/\${PRETIX_POSTGRES_DB}/${{ secrets.PRETIX_POSTGRES_DB }}/g" pretix/init.sql
          sed -i '' "s/\${PRETIX_POSTGRES_PASSWORD}/${{ secrets.PRETIX_POSTGRES_PASSWORD }}/g" pretix/init.sql
      - name: replace pretix config file with env vars
        run: |
          sed -i '' "s/\${PRETIX_POSTGRES_USER}/${{ secrets.PRETIX_POSTGRES_USER }}/g" pretix/etc/pretix.cfg
          sed -i '' "s/\${PRETIX_POSTGRES_DB}/${{ secrets.PRETIX_POSTGRES_DB }}/g" pretix/etc/pretix.cfg
          sed -i '' "s/\${PRETIX_POSTGRES_PASSWORD}/${{ secrets.PRETIX_POSTGRES_PASSWORD }}/g" pretix/etc/pretix.cfg

          sed -i '' "s/\${PRETIX_HOSTNAME}/${{ env.PRETIX_HOSTNAME }}/g" pretix/etc/pretix.cfg
          sed -i '' "s/\${PRETIX_INSTANCE_NAME}/${{ env.PRETIX_INSTANCE_NAME }}/g" pretix/etc/pretix.cfg
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "pretix/*,traefik/*,backups/*"
          target: /opt/
  provision:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    needs:
      - scp-files
    steps:
      - name: Spin up traefik and pretix
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script-stop: true
          envs: POSTGRES_ADMIN_PASSWORD, PRETIX_HOSTNAME, PRETIX_POSTGRES_DB, POSTGRES_ADMIN_PASSWORD,PRETIX_POSTGRES_DB
          script: |
            # Docker stack deploys
            docker stack deploy -c traefik/docker-compose.yml traefik
            docker stack deploy -c pretix/docker-compose.yml pretix
            #docker stack deploy -c backups/docker-compose.yml backup