name: "Pretix deploy"

on:
  push:
    branches:
      - main
jobs:
  scp-files:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Replace env variables in init.sql for pretix postgres database
        run: |
          sed -i "s/\${PRETIX_POSTGRES_USER}/${{ secrets.PRETIX_POSTGRES_USER }}/g" pretix/init.sql
          sed -i "s/\${PRETIX_POSTGRES_DB}/${{ secrets.PRETIX_POSTGRES_DB }}/g" pretix/init.sql
          sed -i "s/\${PRETIX_POSTGRES_PASSWORD}/${{ secrets.PRETIX_POSTGRES_PASSWORD }}/g" pretix/init.sql
      - name: replace pretix config file with env vars
        run: |
          sed -i "s/\${PRETIX_POSTGRES_USER}/${{ secrets.PRETIX_POSTGRES_USER }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_POSTGRES_DB}/${{ secrets.PRETIX_POSTGRES_DB }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_POSTGRES_PASSWORD}/${{ secrets.PRETIX_POSTGRES_PASSWORD }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_MAIL_HOST}/${{ secrets.PRETIX_MAIL_HOST }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_MAIL_USER}/${{ secrets.PRETIX_MAIL_USER }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_MAIL_PASSWORD}/${{ secrets.PRETIX_MAIL_PASSWORD }}/g" pretix/etc/pretix.cfg
          
          sed -i "s/\${PRETIX_HOSTNAME}/${{ vars.PRETIX_HOSTNAME }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_INSTANCE_NAME}/${{ vars.PRETIX_INSTANCE_NAME }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_MAIL_PORT}/${{ vars.PRETIX_MAIL_PORT }}/g" pretix/etc/pretix.cfg
          sed -i "s/\${PRETIX_MAIL_FROM}/${{ vars.PRETIX_MAIL_FROM }}/g" pretix/etc/pretix.cfg
      - name: create .env from .env.example
        run: |
          cp .env.example .env

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "pretix/*,traefik/*,backups/*, .env"
          target: /opt/
  provision:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    needs:
      - scp-files
    steps:
      - name: Spin up traefik and pretix
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script-stop: true
          env_all: true # export all environment variables to remote server
          script: |
            # Docker stack deploys
            sudo docker network create --driver=overlay proxy
            docker stack deploy -c /opt/traefik/docker-compose.yml traefik
            chown -R 15371:15371 ./pretix/etc/
            chmod 0700 ./pretix/etc/pretix.cfg
            docker stack deploy -c /opt/pretix/docker-compose.yml pretix
            #docker stack deploy -c backups/docker-compose.yml backup